clubs:
    path:  /
    defaults: { _controller: "BackendBundle:Club:index" }

club_new:
    path:  /new
    defaults: { _controller: "BackendBundle:Club:new" }

club_create:
    path:  /create
    defaults: { _controller: "BackendBundle:Club:create" }
    methods: POST

club_edit:
    path:  /{id}/edit
    defaults: { _controller: "BackendBundle:Club:edit" }

club_update:
    path:  /{id}/update
    defaults: { _controller: "BackendBundle:Club:update" }
    methods: POST

club_delete:
    path:  /{id}/delete
    defaults: { _controller: "BackendBundle:Club:delete" }
    methods: GET
